### ISSUE TITLE
Unable to initialize skeleton database from remote git 

### ISSUE THREAD

**Issue by ArnieBerg** [c2-d2/rase-db-skeleton#8]
I get the following error when executing the curl command to bring in the rase skeleton database. Any idea what is causing this error?

(raseenv) analynano@analynano:/media/analynano/Data500GB/ArnieFiles/rase-pipeline/database/rasedb$ /usr/bin/env bash -c "$(curl -fsSL https://
raw.githubusercontent.com/c2-d2/rase-db-skeleton/master/init-repo.sh)"

Checking current directory
--------------------------

Checking dependencies
---------------------

Downloading and extracting RASE DB skeleton
-------------------------------------------

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   130    0   130    0     0    459      0 --:--:-- --:--:-- --:--:--   460
100  8238    0  8238    0     0  10984      0 --:--:-- --:--:-- --:--:-- 10984
rase-db-skeleton-master/.gitignore
rase-db-skeleton-master/.gitmodules
rase-db-skeleton-master/LICENSE
rase-db-skeleton-master/Makefile
rase-db-skeleton-master/README.md
rase-db-skeleton-master/Snakefile
rase-db-skeleton-master/_add_rase_paths.sh
rase-db-skeleton-master/_output/
rase-db-skeleton-master/_output/.gitignore
rase-db-skeleton-master/_output/Makefile
rase-db-skeleton-master/conf.mk
rase-db-skeleton-master/docs/
rase-db-skeleton-master/docs/abbreviations.tsv
rase-db-skeleton-master/index/
rase-db-skeleton-master/index/.gitignore
rase-db-skeleton-master/index/Makefile
rase-db-skeleton-master/init-repo.sh
rase-db-skeleton-master/init.mk
rase-db-skeleton-master/isolates/
rase-db-skeleton-master/isolates/.gitignore
rase-db-skeleton-master/isolates/Makefile
rase-db-skeleton-master/isolates/create_example_isolates.sh
rase-db-skeleton-master/plots/
rase-db-skeleton-master/plots/.gitignore
rase-db-skeleton-master/plots/Makefile
rase-db-skeleton-master/published/
rase-db-skeleton-master/published/.gitignore
rase-db-skeleton-master/published/Makefile
rase-db-skeleton-master/published/isolates.example.tsv
rase-db-skeleton-master/published/tree.example.nw
rase-db-skeleton-master/rase/
rase-db-skeleton-master/resistance/
rase-db-skeleton-master/resistance/.gitignore
rase-db-skeleton-master/resistance/Makefile
rase-db-skeleton-master/tree/
rase-db-skeleton-master/tree/.gitignore
rase-db-skeleton-master/tree/Makefile
rase-db-skeleton-master/unpublished/
rase-db-skeleton-master/unpublished/Makefile

Initializing git repository
---------------------------

Initialized empty Git repository in /media/analynano/Data500GB/ArnieFiles/rase-pipeline/database/rasedb/.git/

Adding RASE submodule
---------------------

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   840  100   840    0     0   2295      0 --:--:-- --:--:-- --:--:--  2288
Cloning into '/media/analynano/Data500GB/ArnieFiles/rase-pipeline/database/rasedb/rase'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@github.com/karel-brinda/rase' into submodule path '/media/analynano/Data500GB/ArnieFiles/rase-pipeline/database/rasedb/rase' failed

**Comment by karel-brinda** [comment]
Thanks for reporting. The submodule pointer was mistakenly pointing to a private version of the repository. It should be fixed now (by https://github.com/c2-d2/rase-db-skeleton/commit/1ea4ed825556724faa797e8972f418eb1e229ff2). If not, feel free to reopen this issue.

**Comment by ArnieBerg** [comment]
Unfortunately I still get the same error.  The only difference appears to be the omission of the warning regarding the RSA host key.


Adding RASE submodule
---------------------

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   803  100   803    0     0   2768      0 --:--:-- --:--:-- --:--:--  2768
Cloning into '/media/analynano/Data500GB/ArnieFiles/rase-pipeline/database/rasedb/rase'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@github.com/karel-brinda/rase' into submodule path '/media/analynano/Data500GB/ArnieFiles/rase-pipeline/database/rasedb/rase' failed

**Comment by karel-brinda** [comment]
Could you try it now once again?

**Comment by ArnieBerg** [comment]
That did it!  Cheers, my friend.
